### ISSUE TITLE
Questions/Feature request

### ISSUE THREAD

**Issue by beckend** [zahash/reactivate#2]
Is it possible to use async functions as an observer?

How to stop an observer conditionally?

**Comment by zahash** [comment]
i don't think async mixes well with this library. if you have any ideas on how to make it work, please let me know. its MIT license.

**Comment by beckend** [comment]
Very simple, add _async suffix for methods.
add_oberver_async can return Future<Output = T>
and update_async(...).await;

**Comment by zahash** [comment]
hmmm... let me try it out and see if i can make it work.

**Comment by zahash** [comment]
can you show me some code samples on how you wish to use this in an async context?

**Comment by zahash** [comment]
> Very simple, add _async suffix for methods. add_oberver_async can return Future<Output = T> and update_async(...).await;

@beckend 

can you show me some code samples on how you wish to use this in an async context?

**Comment by beckend** [comment]
```rust
use reactivate::Reactive;

#[tokio::main]
async fn main() {
    let r = Reactive::new(10);
    let d = r.derive(|val| val + 5);
    let scoped_var = 20;
    let fut = r.update_async(move |_| async move {
      tokio::time::sleep(std::time::Duration::from_millis(10)).await;
      Ok(scoped_var)
    });

    println!("{:?}", r); // Reactive(10)
    println!("{:?}", d); // Reactive(15)

    fut.await;

    println!("{:?}", r); // Reactive(20)
    println!("{:?}", d); // Reactive(25)
}

```

**Comment by beckend** [comment]
Justification:
* Read files, databases updates, remote API calls, before we want to trigger an update to the reactive elements.

**Comment by zahash** [comment]
@beckend 

just added the update_async method. can you check the latest version? 0.2.10

i will add the update_async_inplace and update_async_unchecked soon. Is there anything else you want?

**Comment by beckend** [comment]
How about add_observer for async.
Also naming should be identical with async as a suffix and not in the middle.

**Comment by zahash** [comment]
@beckend 
Can you give me a code example of how add_observer_async can be used?

**Comment by beckend** [comment]
```rust
use reactivate::Reactive;
use std::sync::{Arc, Mutex};

fn main() {
    let r: Reactive<String> = Reactive::default();

    let changes: Arc<Mutex<Vec<String>>> = Default::default();

    r.add_observer_async({
        let changes = changes.clone();
        move |val| {
          async move {
            tokio::thread::yield_now().await;
            changes.lock().unwrap().push(val.clone());

            if val == "abcd" {
              Err("abcd".into())
            } else {
              Ok(())
            }
          }
        }
    });

    r.update_async(|_| async {
      Ok(String::from("a"))
    }).await;

    println!("{:?}", r); // Reactive("a")
    println!("{:?}", changes.lock().unwrap().clone()); // ["a"]

    r.update_inplace_async(|s| {
        async move {
          s.push('b');
          Ok(())
        }
    }).await;

    println!("{:?}", r); // Reactive("ab")
    println!("{:?}", changes.lock().unwrap().clone()); // ["a", "ab"]
}

```

The issue is when something is doing sync updates in between the observers, in such cases, I would have a `r.observer_wait().await` or something similar, you decide the API name.

**Comment by zahash** [comment]
@beckend 
i just found out that doing this doesn't work

```rust
    let r = Reactive::new(10);
    let d = r.derive(|val| val + 5);

    r.update_async(|n| async { n + 10 }).await;
```

```sh
error: lifetime may not live long enough
  --> tests/lib_tests.rs:46:24
   |
46 |     r.update_async(|n| async { n + 10 }).await;
   |                     -- ^^^^^^^^^^^^^^^^ returning this value requires that `'1` must outlive `'2`
   |                     ||
   |                     |return type of closure `{async block@tests/lib_tests.rs:46:24: 46:40}` contains a lifetime `'2`
   |                     has type `&'1 i32`

error[E0373]: async block may outlive the current function, but it borrows `n`, which is owned by the current function
  --> tests/lib_tests.rs:46:24
   |
46 |     r.update_async(|n| async { n + 10 }).await;
   |                        ^^^^^^^^-^^^^^^^
   |                        |       |
   |                        |       `n` is borrowed here
   |                        may outlive borrowed value `n`
   |
```

**Comment by beckend** [comment]
Box::pin

**Comment by beckend** [comment]
Otherwise a clone if possible?

**Comment by zahash** [comment]
@beckend 
clone is not an option. If update_async is not possible, I can instead create a `set_async` function.
And I don't want the headache of wrestling with pinning

**Comment by zahash** [comment]
but i think even `set_async` doesn't make sense to have

**Comment by beckend** [comment]
Ok, if this is not possible then close the issue.

**Comment by zahash** [comment]
@beckend 

I really wanted to add this feature. But sadly couldn't. 😞
